import requests
import pandas as pd
import apimoex
import numpy as np

request_url = ('https://iss.moex.com/iss/engines/stock/'
               'markets/shares/boards/TQBR/securities.json')

arguments = {'securities.columns': ('SECID,'
                                    'REGNUMBER,'
                                    'LOTSIZE,'
                                    'SHORTNAME')}
with requests.Session() as session:
    iss = apimoex.ISSClient(session, request_url, arguments)
    data = iss.get()  # здесь только российские акции
    df = pd.DataFrame(data['securities'])

companyNames = {}
for i in range(len(df)):
    companyNames[df.loc[i, 'SECID']] = df.loc[i, 'SHORTNAME']

labels = list(companyNames.keys())


def send_telegram(text: str):
    token = "2119613027:AAHmZRe18BEf7ttw1hSKuFqFKV96MpuzUKw"
    url = "https://api.telegram.org/bot"
    channel_id = "@stockrates"
    url += token
    method = url + "/sendMessage"

    r = requests.post(method, data={
        "chat_id": channel_id,
        "text": text
    })

    print(r.status_code)
    if r.status_code != 200:
        raise Exception("post_text error")
    print(method)


stocksSPB = ['A', 'AA', 'AAL', 'AAN', 'AAON', 'AAP', 'AAPL', 'AAXN', 'ABBV', 'ABC', 'ABCB', 'ABG', 'ABM', 'ABMD',
          'ABNB',
          'ABT', 'ABTX', 'ACA', 'ACAD', 'ACH', 'ACIA', 'ACIW', 'ACLS', 'ACM', 'ACMR', 'ACN', 'ADBE', 'ADI', 'ADM',
          'ADP', 'ADPT', 'ADS', 'ADSK', 'ADUS', 'AEE', 'AEIS', 'AEO', 'AERI', 'AES', 'AFG', 'AFL', 'AFYA', 'AGCO',
          'AGIO', 'AGX', 'AIG', 'AIMC', 'AIN', 'AIR', 'AIRC', 'AIT', 'AIV', 'AIZ', 'AJG', 'AJRD', 'AKAM', 'AKRO',
          'ALB',
          'ALE', 'ALEC', 'ALG', 'ALGN', 'ALGT', 'ALK', 'ALL', 'ALLE', 'ALLK', 'ALLO', 'ALLY', 'ALNY', 'ALRM',
          'ALSN',
          'ALTR', 'ALV', 'ALXN', 'AMAT', 'AMCR', 'AMCX', 'AMD', 'AME', 'AMED', 'AMG', 'AMGN', 'AMN', 'AMP', 'AMSF',
          'AMT', 'AMWD', 'AMX', 'AMZN', 'AN', 'ANAB', 'ANDE', 'ANET', 'ANF', 'ANGI', 'ANIK', 'ANIP', 'ANSS', 'ANTM',
          'AON', 'AOS', 'AOUT', 'APA', 'APAM', 'APD', 'APEI', 'APH', 'APLE', 'APLS', 'APLT', 'APPF', 'APPN', 'APPS',
          'APRE', 'APTV', 'ARCC', 'ARCT', 'ARE', 'ARMK', 'ARNA', 'ARNC', 'ARQT', 'ARVN', 'ARW', 'ARWR', 'ASGN',
          'ASH',
          'ASIX', 'ASMB', 'ASTE', 'ATEX', 'ATGE', 'ATHM', 'ATI', 'ATKR', 'ATNI', 'ATR', 'ATRA', 'ATRC', 'ATRI',
          'ATRO',
          'ATSG', 'ATUS', 'ATVI', 'AVA', 'AVAV', 'AVB', 'AVGO', 'AVLR', 'AVNS', 'AVNT', 'AVT', 'AVTR', 'AVY', 'AWI',
          'AWK', 'AWR', 'AX', 'AXGN', 'AXNX', 'AXP', 'AXSM', 'AXTA', 'AYI', 'AYX', 'AZO', 'AZPN', 'AZZ', 'B', 'BA',
          'BABA', 'BAC', 'BAH', 'BAND', 'BANF', 'BANR', 'BAX', 'BBBY', 'BBIO', 'BBSI', 'BBY', 'BC', 'BCC', 'BCO',
          'BCPC', 'BDC', 'BDTX', 'BDX', 'BEAT', 'BECN', 'BEN', 'BERY', 'BF.B', 'BFAM', 'BGS', 'BH', 'BHF', 'BIDU',
          'BIG', 'BIIB', 'BILI', 'BILL', 'BIO', 'BJ', 'BJRI', 'BK', 'BKI', 'BKNG', 'BKR', 'BKU', 'BL', 'BLD',
          'BLDR',
          'BLK', 'BLKB', 'BLL', 'BLMN', 'BLUE', 'BMCH', 'BMI', 'BMRN', 'BMY', 'BOH', 'BOKF', 'BOOM', 'BOOT', 'BOX',
          'BP', 'BPMC', 'BR', 'BRC', 'BRK.A', 'BRK.B', 'BRKR', 'BRKS', 'BRO', 'BRX', 'BSX', 'BTAI', 'BTI', 'BUD',
          'BURL', 'BWA', 'BWXT', 'BX', 'BXP', 'BYND', 'BZUN', 'C', 'CABO', 'CAC', 'CACC', 'CAG', 'CAH', 'CALM',
          'CARA',
          'CARG', 'CARR', 'CARS', 'CASY', 'CAT', 'CATY', 'CB', 'CBPO', 'CBRE', 'CBRL', 'CBSH', 'CBT', 'CBU', 'CBZ',
          'CC', 'CCC', 'CCI', 'CCK', 'CCL', 'CCMP', 'CCOI', 'CCS', 'CCXI', 'CDK', 'CDLX', 'CDNA', 'CDNS', 'CDW',
          'CE',
          'CEA', 'CENT', 'CENTA', 'CERN', 'CEVA', 'CF', 'CFG', 'CFR', 'CFX', 'CGEN', 'CGNX', 'CHA', 'CHCO', 'CHD',
          'CHDN', 'CHE', 'CHEF', 'CHGG', 'CHH', 'CHKP', 'CHL', 'CHNG', 'CHRW', 'CHTR', 'CHWY', 'CHX', 'CI', 'CIEN',
          'CINF', 'CIT', 'CL', 'CLB', 'CLDR', 'CLDT', 'CLF', 'CLGX', 'CLH', 'CLR', 'CLX', 'CMA', 'CMC', 'CMCO',
          'CMCSA',
          'CMD', 'CME', 'CMG', 'CMI', 'CMP', 'CMS', 'CNA', 'CNC', 'CNK', 'CNMD', 'CNNE', 'CNP', 'CNS', 'CNST',
          'CNX',
          'CNXC', 'CNXN', 'COF', 'COG', 'COHR', 'COKE', 'COLB', 'COLD', 'COLM', 'CONE', 'COO', 'COP', 'COR', 'CORE',
          'CORR', 'CORT', 'COST', 'COTY', 'COUP', 'CPB', 'CPRI', 'CPRT', 'CPS', 'CPSI', 'CR', 'CREE', 'CRI', 'CRL',
          'CRM', 'CRMT', 'CROX', 'CRS', 'CRTX', 'CRUS', 'CRVL', 'CRWD', 'CRY', 'CSCO', 'CSGP', 'CSGS', 'CSII',
          'CSL',
          'CSOD', 'CSTL', 'CSWI', 'CSX', 'CTAS', 'CTB', 'CTLT', 'CTS', 'CTSH', 'CTVA', 'CTXS', 'CUE', 'CVCO',
          'CVET',
          'CVGW', 'CVI', 'CVLT', 'CVNA', 'CVS', 'CVX', 'CW', 'CWEN', 'CWST', 'CWT', 'CXO', 'CYRX', 'CYTK', 'D',
          'DAL',
          'DAR', 'DASH', 'DBX', 'DCI', 'DCOM', 'DCPH', 'DD', 'DDOG', 'DDS', 'DE', 'DECK', 'DELL', 'DFS', 'DG',
          'DGX',
          'DHI', 'DHR', 'DIOD', 'DIS', 'DISCA', 'DISCK', 'DISH', 'DK', 'DKNG', 'DKS', 'DLB', 'DLR', 'DLTH', 'DLTR',
          'DLX', 'DNKN', 'DNLI', 'DNOW', 'DOCU', 'DORM', 'DOV', 'DOW', 'DOYU', 'DPZ', 'DRE', 'DRI', 'DRNA', 'DRQ',
          'DT',
          'DTE', 'DVA', 'DVN', 'DXC', 'DXCM', 'DY', 'EA', 'EAT', 'EBAY', 'EBIX', 'EBS', 'ECHO', 'ECL', 'ECPG', 'ED',
          'EDIT', 'EEFT', 'EFSC', 'EFX', 'EGBN', 'EGHT', 'EGP', 'EGRX', 'EHTH', 'EIDX', 'EIX', 'EL', 'ELAN', 'ELS',
          'EME', 'EMN', 'EMR', 'ENDP', 'ENPH', 'ENR', 'ENS', 'ENSG', 'ENTA', 'ENTG', 'ENV', 'EOG', 'EPAM', 'EPAY',
          'EPC', 'EQIX', 'EQNR', 'EQT', 'ERIE', 'ES', 'ESE', 'ESPR', 'ESS', 'ET', 'ETM', 'ETN', 'ETR', 'ETRN',
          'ETSY',
          'EV', 'EVBG', 'EVER', 'EVH', 'EVR', 'EVRG', 'EW', 'EWBC', 'EXAS', 'EXC', 'EXEL', 'EXLS', 'EXP', 'EXPD',
          'EXPE', 'EXPO', 'EXR', 'EYE', 'F', 'FANG', 'FARO', 'FAST', 'FATE', 'FB', 'FBC', 'FBHS', 'FBK', 'FBNC',
          'FCFS',
          'FCN', 'FCNCA', 'FCX', 'FDS', 'FDX', 'FE', 'FELE', 'FFIN', 'FFIV', 'FGEN', 'FHI', 'FICO', 'FIS', 'FISV',
          'FITB', 'FIVE', 'FIVN', 'FIX', 'FIZZ', 'FL', 'FLIR', 'FLO', 'FLOW', 'FLR', 'FLS', 'FLT', 'FLWS', 'FMC',
          'FND',
          'FNF', 'FNKO', 'FOCS', 'FOE', 'FOLD', 'FORM', 'FORR', 'FOX', 'FOXA', 'FOXF', 'FRHC', 'FRME', 'FRPH',
          'FRPT',
          'FSLR', 'FSLY', 'FSS', 'FTCH', 'FTDR', 'FTI', 'FTNT', 'FTV', 'FUL', 'FWRD', 'GATX', 'GBCI', 'GBT', 'GBX',
          'GCO', 'GCP', 'GD', 'GDDY', 'GDOT', 'GE', 'GEF', 'GGG', 'GH', 'GHC', 'GILD', 'GIS', 'GKOS', 'GL', 'GLIBA',
          'GLPI', 'GLW', 'GM', 'GMED', 'GMS', 'GNL', 'GNRC', 'GNTX', 'GO', 'GOLF', 'GOOG', 'GOOGL', 'GOSS', 'GPC',
          'GPI', 'GPN', 'GPS', 'GRA', 'GRMN', 'GRUB', 'GS', 'GSH', 'GSHD', 'GSKY', 'GT', 'GTHX', 'GTLS', 'GTN',
          'GTY',
          'GVA', 'GWRE', 'GWW', 'H', 'HA', 'HAE', 'HAIN', 'HAL', 'HALO', 'HAS', 'HASI', 'HAYN', 'HBAN', 'HBI',
          'HCA',
          'HCAT', 'HCCI', 'HCSG', 'HD', 'HDS', 'HE', 'HEAR', 'HEI', 'HES', 'HFC', 'HGV', 'HHC', 'HHR', 'HI', 'HIBB',
          'HIG', 'HII', 'HLI', 'HLIO', 'HLNE', 'HLT', 'HMN', 'HMST', 'HNP', 'HOG', 'HOLX', 'HON', 'HP', 'HPE',
          'HPQ',
          'HQY', 'HRB', 'HRC', 'HRL', 'HRTX', 'HSC', 'HSIC', 'HSII', 'HSKA', 'HST', 'HSY', 'HTA', 'HTHT', 'HTLF',
          'HUBB', 'HUBG', 'HUBS', 'HUM', 'HURN', 'HWM', 'HXL', 'HY', 'IAA', 'IAC', 'IART', 'IBKR', 'IBM', 'IBN',
          'IBOC',
          'IBP', 'IBTX', 'ICE', 'ICFI', 'ICPT', 'ICUI', 'IDA', 'IDCC', 'IDXX', 'IEX', 'IFF', 'IGMS', 'IIIV', 'IIPR',
          'IIVI', 'ILMN', 'INCY', 'INDB', 'INFO', 'INGN', 'INGR', 'INMD', 'INSP', 'INT', 'INTC', 'INTU', 'INVH',
          'IONS',
          'IOSP', 'IOVA', 'IP', 'IPAR', 'IPG', 'IPGP', 'IPHI', 'IQV', 'IR', 'IRBT', 'IRDM', 'IRM', 'IRTC', 'ISRG',
          'IT',
          'ITCI', 'ITGR', 'ITRI', 'ITT', 'ITW', 'IVZ', 'J', 'JACK', 'JBHT', 'JBL', 'JBSS', 'JBT', 'JCI', 'JCOM',
          'JD',
          'JEF', 'JELD', 'JHG', 'JJSF', 'JKHY', 'JLL', 'JNJ', 'JNPR', 'JOBS', 'JOUT', 'JPM', 'JWN', 'K', 'KAI',
          'KALU',
          'KAMN', 'KBH', 'KDP', 'KEP', 'KEX', 'KEY', 'KEYS', 'KFRC', 'KFY', 'KHC', 'KIDS', 'KIM', 'KKR', 'KLAC',
          'KLIC',
          'KMB', 'KMI', 'KMPR', 'KMT', 'KMX', 'KNSL', 'KNX', 'KO', 'KOD', 'KR', 'KRG', 'KRTX', 'KRYS', 'KSU', 'KTB',
          'KWR', 'L', 'LAD', 'LANC', 'LASR', 'LB', 'LBRDK', 'LCII', 'LDOS', 'LEA', 'LECO', 'LEG', 'LEGH', 'LEN',
          'LEN.B', 'LEVI', 'LFC', 'LFUS', 'LGIH', 'LGND', 'LH', 'LHCG', 'LHX', 'LII', 'LIN', 'LITE', 'LKFN', 'LKQ',
          'LLY', 'LMAT', 'LMNX', 'LMT', 'LNN', 'LNT', 'LNTH', 'LOPE', 'LORL', 'LOW', 'LPL', 'LPLA', 'LPSN', 'LPX',
          'LRCX', 'LRN', 'LSCC', 'LSTR', 'LTC', 'LTHM', 'LULU', 'LUMN', 'LUV', 'LVS', 'LW', 'LX', 'LYB', 'LYFT',
          'LYV',
          'LZB', 'M', 'MA', 'MAA', 'MAC', 'MAN', 'MANH', 'MANT', 'MANU', 'MAR', 'MAS', 'MASI', 'MAT', 'MATW',
          'MATX',
          'MBT', 'MBUU', 'MC', 'MCD', 'MCHP', 'MCK', 'MCO', 'MCRI', 'MD', 'MDB', 'MDC', 'MDGL', 'MDLA', 'MDLZ',
          'MDRX',
          'MDT', 'MDU', 'MED', 'MEDP', 'MEI', 'MELI', 'MET', 'MFGP', 'MGLN', 'MGM', 'MGPI', 'MGRC', 'MGY', 'MHK',
          'MHO',
          'MIDD', 'MKC', 'MKL', 'MKSI', 'MKTX', 'MLAB', 'MLCO', 'MLHR', 'MLI', 'MLM', 'MMC', 'MMI', 'MMM', 'MMS',
          'MMSI', 'MNRO', 'MNST', 'MO', 'MODN', 'MOH', 'MOMO', 'MORN', 'MOS', 'MOV', 'MPC', 'MPWR', 'MRC', 'MRK',
          'MRNA', 'MRO', 'MRTN', 'MRTX', 'MS', 'MSA', 'MSCI', 'MSEX', 'MSFT', 'MSGE', 'MSGN', 'MSGS', 'MSI', 'MSM',
          'MSTR', 'MT', 'MTB', 'MTCH', 'MTD', 'MTG', 'MTH', 'MTN', 'MTOR', 'MTRN', 'MTSC', 'MTX', 'MU', 'MUR',
          'MUSA',
          'MXIM', 'MXL', 'MYGN', 'MYRG', 'NARI', 'NAT', 'NATI', 'NAVI', 'NBIX', 'NBTB', 'NCBS', 'NCR', 'NDAQ',
          'NDSN',
          'NEE', 'NEM', 'NEO', 'NEOG', 'NET', 'NEU', 'NEWR', 'NFG', 'NFLX', 'NGM', 'NGVT', 'NICE', 'NJR', 'NKE',
          'NKLA',
          'NKTR', 'NLOK', 'NLSN', 'NMIH', 'NOC', 'NOK', 'NOV', 'NOW', 'NP', 'NPK', 'NPO', 'NRG', 'NSC', 'NSIT',
          'NSP',
          'NSSC', 'NTAP', 'NTCO', 'NTCT', 'NTES', 'NTGR', 'NTLA', 'NTNX', 'NTRA', 'NTRS', 'NTUS', 'NUE', 'NUS',
          'NUVA',
          'NVDA', 'NVEE', 'NVR', 'NVRO', 'NVS', 'NVTA', 'NWE', 'NWL', 'NWLI', 'NWS', 'NWSA', 'NXPI', 'NXST', 'NYT',
          'O',
          'OC', 'ODFL', 'OFIX', 'OGE', 'OGS', 'OHI', 'OI', 'OII', 'OIS', 'OKE', 'OKTA', 'OLED', 'OLLI', 'OMC',
          'OMCL',
          'ON', 'ONTO', 'ORCL', 'ORLY', 'OSIS', 'OSK', 'OSUR', 'OTIS', 'OTTR', 'OVV', 'OXM', 'OXY', 'OZON', 'PAG',
          'PAGS', 'PAHC', 'PANW', 'PAR', 'PATK', 'PAYC', 'PB', 'PBCT', 'PBF', 'PBH', 'PBI', 'PBR', 'PCAR', 'PCG',
          'PCRX', 'PCTY', 'PD', 'PDCO', 'PDD', 'PEAK', 'PEBO', 'PEG', 'PEGA', 'PEN', 'PEP', 'PETQ', 'PETS', 'PFE',
          'PFG', 'PFGC', 'PFPT', 'PG', 'PGNY', 'PGR', 'PGTI', 'PH', 'PHAT', 'PHM', 'PII', 'PINC', 'PING', 'PINS',
          'PIPR', 'PJT', 'PKG', 'PKI', 'PLAN', 'PLAY', 'PLCE', 'PLD', 'PLNT', 'PLOW', 'PLTR', 'PLUS', 'PLXS', 'PM',
          'PNC', 'PNFP', 'PNM', 'PNTG', 'PODD', 'POOL', 'POR', 'POST', 'POWI', 'POWL', 'PPC', 'PPG', 'PPL', 'PRAA',
          'PRAH', 'PRFT', 'PRGS', 'PRI', 'PRLB', 'PRO', 'PRSC', 'PRSP', 'PRU', 'PS', 'PSA', 'PSMT', 'PSN', 'PSTG',
          'PSX', 'PTC', 'PTCT', 'PTON', 'PTR', 'PUMP', 'PVH', 'PWR', 'PXD', 'PYPL', 'PZZA', 'QADA', 'QCOM', 'QD',
          'QDEL', 'QLYS', 'QNST', 'QRTEA', 'QRVO', 'QTRX', 'QTS', 'QTWO', 'QUOT', 'R', 'RACE', 'RAMP', 'RARE',
          'RAVN',
          'RBC', 'RCII', 'RCL', 'RCUS', 'RDFN', 'RDS.A', 'RDY', 'RE', 'REG', 'REGI', 'REGN', 'RETA', 'REX', 'REYN',
          'REZI', 'RF', 'RGA', 'RGEN', 'RGLD', 'RGNX', 'RGR', 'RH', 'RHI', 'RIG', 'RJF', 'RL', 'RLMD', 'RMAX',
          'RMD',
          'RMR', 'RNG', 'ROCK', 'ROG', 'ROK', 'ROKU', 'ROL', 'ROLL', 'ROP', 'ROST', 'RP', 'RPD', 'RPM', 'RRBI',
          'RRC',
          'RRGB', 'RS', 'RSG', 'RTX', 'RUSHA', 'RVLV', 'RXN', 'RYN', 'RYTM', 'SAFM', 'SAGE', 'SAH', 'SAIA', 'SAIC',
          'SAIL', 'SAM', 'SANM', 'SAP', 'SASR', 'SATS', 'SAVE', 'SBAC', 'SBCF', 'SBGI', 'SBH', 'SBRA', 'SBSI',
          'SBUX',
          'SCCO', 'SCHL', 'SCHW', 'SCI', 'SCL', 'SCSC', 'SCVL', 'SDGR', 'SEDG', 'SEE', 'SEIC', 'SF', 'SFBS', 'SFIX',
          'SFM', 'SGEN', 'SHAK', 'SHEN', 'SHI', 'SHOO', 'SHW', 'SIG', 'SIGI', 'SILK', 'SINA', 'SITE', 'SITM',
          'SIVB',
          'SJI', 'SJM', 'SJW', 'SKM', 'SKX', 'SLAB', 'SLB', 'SLG', 'SLGN', 'SLP', 'SMAR', 'SMG', 'SMP', 'SMPL',
          'SMTC',
          'SNA', 'SNAP', 'SNBR', 'SNDR', 'SNEX', 'SNPS', 'SNX', 'SNY', 'SO', 'SOHU', 'SON', 'SONO', 'SP', 'SPB',
          'SPCE',
          'SPG', 'SPGI', 'SPLK', 'SPOT', 'SPR', 'SPSC', 'SPXC', 'SQ', 'SR', 'SRC', 'SRCE', 'SRCL', 'SRDX', 'SRE',
          'SRI',
          'SRPT', 'SSD', 'SSNC', 'SSTI', 'SSTK', 'STAA', 'STAG', 'STBA', 'STC', 'STLD', 'STMP', 'STOK', 'STRA',
          'STT',
          'STX', 'STZ', 'SUPN', 'SWAV', 'SWBI', 'SWCH', 'SWI', 'SWK', 'SWKS', 'SWM', 'SWN', 'SWTX', 'SWX', 'SXI',
          'SXT',
          'SYF', 'SYK', 'SYKE', 'SYNA', 'SYNH', 'SYY', 'T', 'TAK', 'TAL', 'TAP', 'TBK', 'TCBI', 'TCBK', 'TCDA',
          'TCMD',
          'TCRR', 'TCS', 'TCX', 'TDC', 'TDG', 'TDOC', 'TDS', 'TDY', 'TECH', 'TEL', 'TENB', 'TER', 'TEVA', 'TFC',
          'TFX',
          'TGNA', 'TGT', 'THG', 'THO', 'THRM', 'THS', 'TIF', 'TJX', 'TKR', 'TMHC', 'TMO', 'TMUS', 'TMX', 'TNC',
          'TNDM',
          'TNET', 'TOL', 'TOT', 'TPB', 'TPH', 'TPIC', 'TPR', 'TPTX', 'TPX', 'TREE', 'TREX', 'TRHC', 'TRIP', 'TRMB',
          'TRMK', 'TRNO', 'TROW', 'TRS', 'TRU', 'TRUP', 'TRV', 'TSCO', 'TSLA', 'TSM', 'TSN', 'TT', 'TTC', 'TTD',
          'TTEC',
          'TTEK', 'TTGT', 'TTM', 'TTMI', 'TTWO', 'TW', 'TWLO', 'TWNK', 'TWOU', 'TWST', 'TWTR', 'TXG', 'TXN', 'TXRH',
          'TXT', 'TYL', 'UA', 'UAA', 'UAL', 'UBER', 'UBSI', 'UCTT', 'UDR', 'UEIC', 'UFCS', 'UFPI', 'UFS', 'UGI',
          'UHS',
          'UI', 'ULTA', 'UMBF', 'UNF', 'UNH', 'UNM', 'UNP', 'UNVR', 'UPS', 'UPWK', 'URBN', 'URI', 'USB', 'USFD',
          'USM',
          'USNA', 'USPH', 'UTHR', 'UTL', 'UVV', 'V', 'VAC', 'VALE', 'VAR', 'VC', 'VCEL', 'VCRA', 'VCYT', 'VEC',
          'VEEV',
          'VEON', 'VFC', 'VG', 'VIAC', 'VICR', 'VIE', 'VIPS', 'VIR', 'VIRT', 'VLO', 'VMC', 'VMI', 'VMW', 'VNDA',
          'VNE',
          'VNO', 'VNT', 'VOD', 'VPG', 'VREX', 'VRNS', 'VRNT', 'VRSK', 'VRSN', 'VRTS', 'VRTU', 'VRTV', 'VRTX',
          'VSAT',
          'VTR', 'VTRS', 'VZ', 'W', 'WAB', 'WABC', 'WAFD', 'WAL', 'WAT', 'WB', 'WBA', 'WBS', 'WCC', 'WDAY', 'WDC',
          'WDFC', 'WEC', 'WELL', 'WERN', 'WEX', 'WFC', 'WGO', 'WH', 'WHD', 'WHR', 'WING', 'WIRE', 'WISH', 'WK',
          'WLK',
          'WLTW', 'WM', 'WMB', 'WMS', 'WMT', 'WOR', 'WORK', 'WRB', 'WRK', 'WRLD', 'WSC', 'WSFS', 'WSM', 'WSO',
          'WST',
          'WTFC', 'WTRG', 'WTS', 'WTTR', 'WU', 'WW', 'WWD', 'WWE', 'WWW', 'WY', 'WYND', 'WYNN', 'XEC', 'XEL',
          'XLNX',
          'XLRN', 'XNCR', 'XOM', 'XP', 'XPO', 'XRAY', 'XRX', 'XYL', 'Y', 'YELP', 'YETI', 'YEXT', 'YMAB', 'YUM',
          'YUMC',
          'YY', 'Z', 'ZBH', 'ZBRA', 'ZEN', 'ZG', 'ZGNX', 'ZI', 'ZION', 'ZM', 'ZNH', 'ZS', 'ZTS', 'ZUMZ', 'ZUO',
          'ZYNE',
          'ZYXI']

stocksMOEX = ['A', 'AA', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABMD', 'ABNB',
       'ABRD', 'ABT', 'ACAD', 'ACKO', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK',
       'AEE', 'AEP', 'AES', 'AFKS', 'AFL', 'AFLT', 'AIG', 'AIZ', 'AJG',
       'AKAM', 'AKRN', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALNU', 'ALRS',
       'AMAT', 'AMC', 'AMD', 'AME', 'AMEZ', 'AMGN', 'AMP', 'AMZN', 'ANET',
       'ANSS', 'ANTM', 'AOS', 'APA', 'APD', 'APH', 'APTK', 'AQUA', 'ARSA',
       'ASSB', 'ATO', 'ATVI', 'AVAN', 'AVGO', 'AVY', 'AWK', 'AXP', 'AYX',
       'AZO', 'BA', 'BAC', 'BANE', 'BANEP', 'BAX', 'BBBY', 'BBWI', 'BBY',
       'BDX', 'BELU', 'BEN', 'BFB', 'BIIB', 'BIO', 'BISV', 'BISVP', 'BK',
       'BKNG', 'BKR', 'BLK', 'BLL', 'BLNG', 'BLUE', 'BMY', 'BNGO', 'BR',
       'BRKB', 'BRZL', 'BSPB', 'BSPBP', 'BSX', 'BWA', 'BYND', 'C', 'CAG',
       'CAH', 'CARR', 'CAT', 'CBOM', 'CDNS', 'CDW', 'CE', 'CERN', 'CF',
       'CFG', 'CHD', 'CHEP', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CHRW',
       'CHTR', 'CI', 'CINF', 'CL', 'CLF', 'CLOV', 'CLX', 'CMA', 'CMCSA',
       'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNK', 'CNP', 'CNTL', 'CNTLP',
       'COF', 'COIN', 'COO', 'COP', 'COST', 'COTY', 'CPB', 'CPNG', 'CPRT',
       'CRL', 'CRM', 'CSCO', 'CSX', 'CTAS', 'CTLT', 'CTRA', 'CTSH',
       'CTVA', 'CTXS', 'CVS', 'CVX', 'CZR', 'D', 'DAL', 'DBX', 'DD', 'DE',
       'DERZP', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIOD', 'DIS', 'DISCA',
       'DISH', 'DKNG', 'DLTR', 'DOV', 'DOW', 'DPZ', 'DRI', 'DSKY', 'DUK',
       'DVA', 'DVEC', 'DVN', 'DXC', 'DXCM', 'DZRD', 'DZRDP', 'EA', 'EBAY',
       'ECL', 'ED', 'EELT', 'EFX', 'EHTH', 'EIX', 'EL', 'ELTZ', 'EMN',
       'EMR', 'ENPG', 'ENPH', 'ENRU', 'EOG', 'EQT', 'ES', 'ETR', 'ETSY',
       'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'F', 'FANG', 'FAST', 'FB',
       'FBHS', 'FCX', 'FDX', 'FE', 'FEES', 'FESH', 'FFIV', 'FIS', 'FISV',
       'FITB', 'FLOT', 'FLT', 'FMC', 'FNKO', 'FOX', 'FSLR', 'FSLY',
       'FTNT', 'FTV', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS', 'GAZT',
       'GCHE', 'GD', 'GE', 'GEMA', 'GEVO', 'GILD', 'GIS', 'GLW', 'GM',
       'GMKN', 'GNRC', 'GOOG', 'GPC', 'GPN', 'GPS', 'GS', 'GT', 'GTHX',
       'GTRK', 'GTSS', 'GWW', 'HAL', 'HAS', 'HBAN', 'HBI', 'HCA', 'HD',
       'HES', 'HIG', 'HII', 'HIMC', 'HIMCP', 'HLT', 'HOLX', 'HON', 'HOOD',
       'HPE', 'HPQ', 'HRL', 'HRTX', 'HSIC', 'HSY', 'HUM', 'HWM', 'HYDR',
       'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'IGST', 'IGSTP', 'ILMN',
       'INCY', 'INGR', 'INTC', 'INTU', 'IP', 'IPG', 'IPGP', 'IQV', 'IR',
       'IRAO', 'IRGZ', 'IRKT', 'ISKJ', 'ISRG', 'IT', 'ITW', 'J', 'JBHT',
       'JKHY', 'JNJ', 'JNOS', 'JNOSP', 'JNPR', 'JPM', 'K', 'KAZT',
       'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KD', 'KDP', 'KEY', 'KEYS',
       'KGKC', 'KGKCP', 'KHC', 'KLAC', 'KLSB', 'KMAZ', 'KMB', 'KMEZ',
       'KMI', 'KMTZ', 'KMX', 'KO', 'KOGK', 'KR', 'KRKN', 'KRKNP', 'KRKO',
       'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KSGR', 'KSU', 'KTSB',
       'KTSBP', 'KUBE', 'KUZB', 'KZMS', 'KZOS', 'KZOSP', 'L', 'LAZR',
       'LDOS', 'LEG', 'LEN', 'LENT', 'LH', 'LHX', 'LIFE', 'LKOH', 'LKQ',
       'LLY', 'LMT', 'LNC', 'LNT', 'LNZL', 'LNZLP', 'LOW', 'LPSB', 'LRCX',
       'LSNG', 'LSNGP', 'LSRG', 'LTHM', 'LUMN', 'LUV', 'LVHK', 'LVS',
       'LW', 'LYFT', 'LYV', 'M', 'MA', 'MAGE', 'MAGEP', 'MAGN', 'MAR',
       'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MET', 'MFGS', 'MFGSP',
       'MFON', 'MGM', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MHK', 'MISB',
       'MISBP', 'MKC', 'MKTX', 'MLM', 'MMC', 'MMM', 'MNST', 'MO', 'MOEX',
       'MORI', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRKC', 'MRKK', 'MRKP',
       'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRNA', 'MRO', 'MRSB',
       'MRVL', 'MS', 'MSCI', 'MSFT', 'MSI', 'MSNG', 'MSRS', 'MSTR',
       'MSTT', 'MTB', 'MTD', 'MTLR', 'MTLRP', 'MTSS', 'MU', 'MVID',
       'MVIS', 'NAUK', 'NDAQ', 'NEE', 'NEM', 'NFAZ', 'NFLX', 'NI', 'NKE',
       'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NLOK', 'NMTP', 'NNSB',
       'NNSBP', 'NOC', 'NOV', 'NOW', 'NPOF', 'NRG', 'NSC', 'NSVZ', 'NTAP',
       'NTRS', 'NUE', 'NVDA', 'NVR', 'NVTK', 'NWL', 'NWS', 'ODFL', 'OGKB',
       'OGN', 'OKE', 'OMC', 'OMZZP', 'ON', 'ORCL', 'ORLY', 'ORUP', 'OSUR',
       'OTIS', 'OXY', 'PAYC', 'PAYX', 'PAZA', 'PBCT', 'PBF', 'PCAR',
       'PCG', 'PEG', 'PENN', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH',
       'PHM', 'PHOR', 'PIKK', 'PINS', 'PKG', 'PKI', 'PLTR', 'PLUG',
       'PLZL', 'PM', 'PMSB', 'PMSBP', 'PNC', 'POGR', 'POLY', 'POOL',
       'PPG', 'PPL', 'PRMB', 'PRU', 'PSX', 'PTC', 'PTON', 'PVH', 'PWR',
       'PXD', 'PYPL', 'QCOM', 'QDEL', 'QRVO', 'QS', 'RASP', 'RAVN',
       'RBCM', 'RDRB', 'REGI', 'REGN', 'RENI', 'RF', 'RGSS', 'RHI',
       'RIDE', 'RJF', 'RKKE', 'RL', 'RMD', 'RNFT', 'ROK', 'ROL', 'ROLO',
       'ROP', 'ROSB', 'ROSN', 'ROST', 'ROST', 'RSG', 'RSTI', 'RSTIP',
       'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RTX', 'RUAL', 'RUGR',
       'RUN', 'RUSI', 'RUSP', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP',
       'SBER', 'SBERP', 'SBUX', 'SCCO', 'SCHW', 'SEDG', 'SEE', 'SELG',
       'SELGP', 'SFIN', 'SGZH', 'SHW', 'SIBN', 'SIVB', 'SJM', 'SKLZ',
       'SLEN', 'SMLT', 'SNA', 'SNAP', 'SNGS', 'SNGSP', 'SNPS', 'SO',
       'SPBE', 'SPCE', 'SPGI', 'SPLK', 'SQ', 'SRE', 'SRPT', 'STSB',
       'STSBP', 'STT', 'STZ', 'SVAV', 'SWK', 'SWKS', 'SWN', 'SYF', 'SYK',
       'SYY', 'T', 'TAP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TDG', 'TDOC',
       'TDY', 'TER', 'TFC', 'TFX', 'TGKA', 'TGKB', 'TGKBP', 'TGKD',
       'TGKDP', 'TGKN', 'TGT', 'TJX', 'TMO', 'TMUS', 'TNSE', 'TORS',
       'TORSP', 'TPR', 'TRCN', 'TRFM', 'TRMB', 'TRMK', 'TRNFP', 'TROW',
       'TRV', 'TSCO', 'TSLA', 'TSN', 'TSVT', 'TTD', 'TTLK', 'TTWO',
       'TUZA', 'TWTR', 'TXN', 'TXT', 'TYL', 'UA', 'UAL', 'UBER', 'UCSS',
       'UHS', 'UKUZ', 'ULTA', 'UNAC', 'UNH', 'UNKL', 'UNM', 'UNP', 'UPRO',
       'UPS', 'URI', 'URKA', 'URKZ', 'USB', 'USBN', 'UTAR', 'V',
       'VEON-RX', 'VFC', 'VGSB', 'VGSBP', 'VIAC', 'VJGZ', 'VJGZP', 'VLHZ',
       'VLO', 'VMC', 'VNT', 'VRSB', 'VRSBP', 'VRSK', 'VRSN', 'VRTX',
       'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'VTRS', 'VUZI', 'VXRT', 'VZ',
       'WAB', 'WAT', 'WBA', 'WDC', 'WEC', 'WFC', 'WHR', 'WISH', 'WM',
       'WMB', 'WMT', 'WRB', 'WRK', 'WST', 'WTCM', 'WTCMP', 'WU', 'WYNN',
       'XEL', 'XLNX', 'XOM', 'XRAY', 'XYL', 'YAKG', 'YKEN', 'YKENP',
       'YNDX', 'YRSB', 'YRSBP', 'YUM', 'ZBH', 'ZBRA', 'ZILL', 'ZION',
       'ZM', 'ZTS', 'ZVEZ', 'ZYNE']




def createForeignStockDF(stocks=stocksMOEX):
    data = {'company': stocks, 'priceHour': list(np.zeros(len(stocks))), 'priceDay': list(np.zeros(len(stocks))),
            'priceWeek': list(np.zeros(len(stocks))), 'priceMonth': list(np.zeros(len(stocks)))}

    dfForeignStocks = pd.DataFrame.from_dict(data)
    dfForeignStocks.set_index('company', inplace=True)
    dfForeignStocks['priceHour'] = 1
    dfForeignStocks['priceDay'] = 1
    dfForeignStocks['priceWeek'] = 1
    dfForeignStocks['priceMonth'] = 1
    dfForeignStocks.to_csv('dfForeignStocks.csv', encoding='utf-8')

    return dfForeignStocks


if __name__ == '__main__':
    createForeignStockDF()
